### ISSUE TITLE
默认探测端口和插件调用

### ISSUE THREAD

**Issue by starnightcyber** [smallcham/sec-admin#12]
1、请问默认探测的端口列表是？
简单翻了下代码，用的是nmap3的nmap_tcp_scan()。
这个其实应该是nmap -sT 参数，不知道默认是扫的nmap的默认常见端口？ 
nmap3还有个scan_top_ports()函数。

2、插件调用
https://github.com/smallcham/sec-admin/blob/57f683aadf4a5200fb68fa38973f749f643b276b/app.py#L417
我看是手工码进去的，可以采用python importlib 动态加载插件的形式。

**Comment by smallcham** [comment]
> 1、请问默认探测的端口列表是？
> 简单翻了下代码，用的是nmap3的nmap_tcp_scan()。
> 这个其实应该是nmap -sT 参数，不知道默认是扫的nmap的默认常见端口？
> nmap3还有个scan_top_ports()函数。
> 
> 2、插件调用
> https://github.com/smallcham/sec-admin/blob/57f683aadf4a5200fb68fa38973f749f643b276b/app.py#L417
> 
> 
> 我看是手工码进去的，可以采用python importlib 动态加载插件的形式。

端口探测是nmap默认的列表, 全端口扫太慢了, 如果需要可以自行改一下.
插件调用的方式用的就是importlib, 代码在执行引擎中: https://github.com/wanzywang/sec-scannode/blob/fbc0028ce51a3e3a4c0a743aeeb7c25b4d9f1932/VulRun.py#L43

**Comment by starnightcyber** [comment]
1 好的。
2 OK.  但在app.py里是用mapper.add_plugin一个个将已有的插件mapper进去的，新增脚本也要加这么一行吗？
感觉可以再写一个函数，来做mapper.add_plugin这个事。

**Comment by smallcham** [comment]
> 1 好的。
> 2 OK. 但在app.py里是用mapper.add_plugin一个个将已有的插件mapper进去的，新增脚本也要加这么一行吗？
> 感觉可以再写一个函数，来做mapper.add_plugin这个事。

不需要, app.py里面只是初始化预置的脚本, 新增的脚本直接在后台有功能可以添加.

**Comment by starnightcyber** [comment]
good ~
