### ISSUE TITLE
脚本扫描速度

### ISSUE THREAD

**Issue by xidaner** [smallcham/sec-admin#15]
大哥，我这里测试爆破一个ssh大概花了10分钟左右 账户密码是root toor 是不是有点慢啊😂

**Comment by smallcham** [comment]
ssh扫描默认的脚本连接超时时间是5秒，认证超时时间是10秒， 你可以在脚本设置里面把超时时间改短，这个依据情况可以调整脚本.

**Comment by xidaner** [comment]
可我试试看

**Comment by xidaner** [comment]
提升速度就没有准确性了 直接扫不出来还行😂
