### ISSUE TITLE
docker一键部署报错

### ISSUE THREAD

**Issue by littleheary** [smallcham/sec-admin#3]
(Background on this error at: http://sqlalche.me/e/e3q8)
(MySQLdb._exceptions.OperationalError) (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
(Background on this error at: http://sqlalche.me/e/e3q8)
(MySQLdb._exceptions.OperationalError) (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
(Background on this error at: http://sqlalche.me/e/e3q8)
(MySQLdb._exceptions.OperationalError) (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
(Background on this error at: http://sqlalche.me/e/e3q8)
(MySQLdb._exceptions.OperationalError) (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
(Background on this error at: http://sqlalche.me/e/e3q8)
(MySQLdb._exceptions.OperationalError) (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
(Background on this error at: http://sqlalche.me/e/e3q8)
(MySQLdb._exceptions.OperationalError) (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
(Background on this error at: http://sqlalche.me/e/e3q8)
(MySQLdb._exceptions.OperationalError) (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")

报上述错误，然后就一直都跑不起来

**Comment by littleheary** [comment]
问题二，通过分布式部署，控制台没有打印密码出来。这怎么搞？
启动命令如下
docker run -d -p 8793:80 --name sec --env HOST=http://0.0.0.0:8793 --env DB_URL=root:secpassword@1.1.2.15:33306/sec --env RDS_URL=0:@1.1.2.15:6379 -v ~/sec-script:/soft/web/sec-admin/sec-admin/static/plugin/usr smallcham/sec:core-0.2 && docker logs -f sec --tail 10

输出内容如下
![image](https://user-images.githubusercontent.com/26987382/79236365-6fdee580-7e9f-11ea-9339-ba2d31130846.png)

**Comment by littleheary** [comment]
我去docker里看了一下，初始化密码是执行
curl -X POST 'http://1.1.2.15:8793/api/system/init'
但是，我手工执行了一下，没有任何回显。
![image](https://user-images.githubusercontent.com/26987382/79238431-f268a480-7ea1-11ea-9c6e-eb11eb7e9357.png)

**Comment by smallcham** [comment]
> 我去docker里看了一下，初始化密码是执行
> curl -X POST 'http://1.1.2.15:8793/api/system/init'
> 但是，我手工执行了一下，没有任何回显。
> ![image](https://user-images.githubusercontent.com/26987382/79238431-f268a480-7ea1-11ea-9c6e-eb11eb7e9357.png)

如果密码没显示的话， 可以直接看这个文件： /var/www/html/sec-admin/init_pwd.sh

**Comment by smallcham** [comment]
> 1.1.2.15:33306

可以在容器里安装一下mysql客户端，apt-get -y update && apt-get -y install mysql-client 连一下你配置的mysql， 看看通不通

**Comment by smallcham** [comment]
> 问题二，通过分布式部署，控制台没有打印密码出来。这怎么搞？
> 启动命令如下
> docker run -d -p 8793:80 --name sec --env HOST=http://0.0.0.0:8793 --env DB_URL=root:secpassword@1.1.2.15:33306/sec --env RDS_URL=0:@1.1.2.15:6379 -v ~/sec-script:/soft/web/sec-admin/sec-admin/static/plugin/usr smallcham/sec:core-0.2 && docker logs -f sec --tail 10
> 
> 输出内容如下
> ![image](https://user-images.githubusercontent.com/26987382/79236365-6fdee580-7e9f-11ea-9339-ba2d31130846.png)

可以在容器里安装一下mysql客户端，apt-get -y update && apt-get -y install mysql-client 连一下你配置的mysql， 看看通不通

**Comment by smallcham** [comment]
> (Background on this error at: http://sqlalche.me/e/e3q8)
> (MySQLdb._exceptions.OperationalError) (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
> (Background on this error at: http://sqlalche.me/e/e3q8)
> (MySQLdb._exceptions.OperationalError) (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
> (Background on this error at: http://sqlalche.me/e/e3q8)
> (MySQLdb._exceptions.OperationalError) (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
> (Background on this error at: http://sqlalche.me/e/e3q8)
> (MySQLdb._exceptions.OperationalError) (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
> (Background on this error at: http://sqlalche.me/e/e3q8)
> (MySQLdb._exceptions.OperationalError) (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
> (Background on this error at: http://sqlalche.me/e/e3q8)
> (MySQLdb._exceptions.OperationalError) (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
> (Background on this error at: http://sqlalche.me/e/e3q8)
> (MySQLdb._exceptions.OperationalError) (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
> 
> 报上述错误，然后就一直都跑不起来

一键部署的如果有问题建议删掉，然后重新run一个 docker rm -f sec && docker run -d -p 8793:80 --name sec --env NODE_COUNT=3 smallcham/sec:all-in-0.2 && docker logs -f sec --tail 10

**Comment by littleheary** [comment]
我是docker分布式部署，mysql是导入的那个create_sql文件，sec数据库正常存在在mysql中，全部docker容器我都stop并rm以后，再次启动了一遍，那个密码还是没打印出来。

我查看sec数据库，发现里面user表是有密码信息的，pass和salt都各自有一串字符串。

但是就是没打印出来，尴尬

**Comment by smallcham** [comment]
> 我是docker分布式部署，mysql是导入的那个create_sql文件，sec数据库正常存在在mysql中，全部docker容器我都stop并rm以后，再次启动了一遍，那个密码还是没打印出来。
> 
> 我查看sec数据库，发现里面user表是有密码信息的，pass和salt都各自有一串字符串。
> 
> 但是就是没打印出来，尴尬

谢谢你的反馈， 如果容器内的 /var/www/html/sec-admin/init_pwd.sh 这个文件也看不到密码的话，  你可以将root的密码和salt改成这个  update sec.user set salt = 'f5ff932772142a429b08c25957f48ba7', pass_word='c2ea586c40caa5742d15d2f18f6fdd3a' where user_name = 'root';   然后使用  test123 作为密码登录后修改
