### ISSUE TITLE
超链接错误

### ISSUE THREAD

**Issue by buyaoyongroot** [smallcham/sec-admin#6]
docker部署后 打开任务计划-执行脚本
http://localhost:8000/static/plugin/usr/MySQL%E5%BC%B1%E5%8F%A3%E4%BB%A4%E6%89%AB%E6%8F%8F[3306]_06606a8b-6a0f-4559-97af-d150770dbcdd.py
应改为./static/plugin/usr/MySQL%E5%BC%B1%E5%8F%A3%E4%BB%A4%E6%89%AB%E6%8F%8F[3306]_06606a8b-6a0f-4559-97af-d150770dbcdd.py
不应该加host

**Comment by smallcham** [comment]
host是启动容器的时候指定的参数，这个参数应该指定你的访问链接，目的是为了兼容多节点部署这样在其它节点上传的脚本也可以被读取，如果host参数指定了localhost 那么容器会找容器内部的本地而不是你的物理机，你应该将--env HOST=你物理机的ip加访问端口

**Comment by smallcham** [comment]
你可以参考以下命令:
docker run -d -p 8793:80 --name sec --env HOST=http://192.168.0.107:8793 --env DB_URL=root:abcd1234@192.168.0.107:3306/sec --env RDS_URL=0:abcd1234@192.168.0.107:6379 -v ~/sec-script:/var/www/html/sec-admin/static/plugin/usr smallcham/sec:core-0.2 && docker logs -f sec --tail 10

一键部署方式仅用于测试，建议使用分布式部署
